# Generated by Django 4.2.7 on 2025-05-06 08:20

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_interface', '0030_theme_collapsible_stacked_inlines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('hero_image_alt', models.CharField(blank=True, max_length=255)),
                ('hero_box_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='admin_interface.theme')),
            ],
        ),
    ]
