# Generated by Django 4.2.7 on 2025-05-06 09:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedtheme',
            name='hero_box_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
