# Generated by Django 4.2.7 on 2025-05-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_alter_extendedtheme_hero_box_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedtheme',
            name='show_navbar',
            field=models.BooleanField(default=True, help_text='Toggle display of category navbar on homepage'),
        ),
    ]
