# Generated by Django 4.2.7 on 2025-05-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_extendedtheme_show_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedtheme',
            name='external_hero_image',
            field=models.URLField(blank=True, help_text='External URL for hero image. This takes precedence over uploaded image.', null=True),
        ),
    ]
