# Generated by Django 4.2.7 on 2025-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='side_image_1',
            field=models.ImageField(blank=True, help_text='Optional image to float left of content on large screens.', null=True, upload_to='posts/side_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='side_image_2',
            field=models.ImageField(blank=True, help_text='Optional image to float right of content on large screens.', null=True, upload_to='posts/side_images/'),
        ),
    ]
