# Generated by Django 4.2.7 on 2025-05-09 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_side_image_1_post_side_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Posts with 'draft' status and future date will be automatically published at this time."),
        ),
    ]
